#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
#  Pachul Installer
#  A powerful Pacman/AUR front end using GTK4 and libadwaita
#  https://github.com/wergosam/Pachul
# ──────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}${BOLD}[·]${RESET} $*"; }
success() { echo -e "${GREEN}${BOLD}[✓]${RESET} $*"; }
warn()    { echo -e "${YELLOW}${BOLD}[!]${RESET} $*"; }
error()   { echo -e "${RED}${BOLD}[✗]${RESET} $*" >&2; }
die()     { error "$*"; exit 1; }

# ── Paths ─────────────────────────────────────────────────────────────────────
APP_NAME="pachul"
INSTALL_DIR="/usr/local/bin"
DATA_DIR="/usr/local/share/${APP_NAME}"
DESKTOP_DIR="/usr/share/applications"
ICON_DIR="/usr/share/icons/hicolor/scalable/apps"
ICON_ID="io.github.wergosam.pachul"
DESKTOP_FILE="${DESKTOP_DIR}/${ICON_ID}.desktop"
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Application Python modules (relative to SRC_DIR)
PY_MODULES=(app.py backend.py dialogs.py i18n.py models.py styles.py window.py notifier.py)

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "
Pachul — Pacman/AUR Front End — Installer v1.0.0
"

# ── Root check ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    warn "Not running as root — re-launching with sudo…"
    exec sudo bash "$0" "$@"
fi

# ── Arch Linux check ──────────────────────────────────────────────────────────
if ! command -v pacman &>/dev/null; then
    die "Pachul requires Arch Linux (pacman not found)."
fi

# ── Source file check ─────────────────────────────────────────────────────────
info "Checking source files…"
MISSING_FILES=()
for f in "${PY_MODULES[@]}"; do
    [[ -f "${SRC_DIR}/${f}" ]] || MISSING_FILES+=("$f")
done
[[ -f "${SRC_DIR}/${ICON_ID}.svg" ]] || MISSING_FILES+=("${ICON_ID}.svg")

if [[ ${#MISSING_FILES[@]} -gt 0 ]]; then
    die "Missing files in ${SRC_DIR}:\n$(printf '   • %s\n' "${MISSING_FILES[@]}")"
fi
success "All source files present."

# ─────────────────────────────────────────────────────────────────────────────
#  1. Dependencies
# ─────────────────────────────────────────────────────────────────────────────
info "Checking dependencies…"

REQUIRED_PKGS=(python gtk4 libadwaita python-gobject pacman-contrib libnotify)
MISSING_PKGS=()
for pkg in "${REQUIRED_PKGS[@]}"; do
    pacman -Qi "$pkg" &>/dev/null || MISSING_PKGS+=("$pkg")
done

if [[ ${#MISSING_PKGS[@]} -gt 0 ]]; then
    warn "Installing missing packages: ${MISSING_PKGS[*]}"
    pacman -Sy --noconfirm --needed "${MISSING_PKGS[@]}" || die "Failed to install dependencies."
    success "Dependencies installed."
else
    success "All dependencies satisfied."
fi

# ─────────────────────────────────────────────────────────────────────────────
#  2. Install application modules
# ─────────────────────────────────────────────────────────────────────────────
info "Installing Pachul modules to ${DATA_DIR}…"

install -d "$DATA_DIR"
for f in "${PY_MODULES[@]}"; do
    install -m 644 "${SRC_DIR}/${f}" "${DATA_DIR}/${f}"
done
success "Modules installed."

# ─────────────────────────────────────────────────────────────────────────────
#  3. Launcher wrapper
# ─────────────────────────────────────────────────────────────────────────────
info "Creating launcher at ${INSTALL_DIR}/${APP_NAME}…"

cat > "${INSTALL_DIR}/${APP_NAME}" <<EOF
#!/usr/bin/env bash
# Pachul launcher — generated by install.sh
export PYTHONPATH="${DATA_DIR}:\${PYTHONPATH:-}"
exec python3 "${DATA_DIR}/app.py" "\$@"
EOF
chmod 755 "${INSTALL_DIR}/${APP_NAME}"
success "Launcher created."

# ─────────────────────────────────────────────────────────────────────────────
#  4. Desktop entry
# ─────────────────────────────────────────────────────────────────────────────
info "Creating desktop entry…"

install -d "$DESKTOP_DIR"
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=Pachul
GenericName=Package Manager
Comment=A powerful Pacman/AUR front end
Exec=${INSTALL_DIR}/${APP_NAME}
Icon=${ICON_ID}
Categories=System;PackageManager;
Keywords=pacman;aur;packages;arch;
Terminal=false
StartupWMClass=pachul
EOF
success "Desktop entry created."

# ─────────────────────────────────────────────────────────────────────────────
#  5. Icon
# ─────────────────────────────────────────────────────────────────────────────
info "Installing icon…"

install -d "$ICON_DIR"
install -m 644 "${SRC_DIR}/${ICON_ID}.svg" "${ICON_DIR}/${ICON_ID}.svg"
gtk-update-icon-cache -f -t /usr/share/icons/hicolor &>/dev/null || true
success "Icon installed."

# ─────────────────────────────────────────────────────────────────────────────
#  6. Update desktop database
# ─────────────────────────────────────────────────────────────────────────────
update-desktop-database "$DESKTOP_DIR" &>/dev/null || true

# ─────────────────────────────────────────────────────────────────────────────
#  Done
# ─────────────────────────────────────────────────────────────────────────────
echo
echo -e "${GREEN}${BOLD}  Pachul installed successfully!${RESET}"
echo
echo -e "  Installed modules  : ${BOLD}${DATA_DIR}/${RESET}"
printf  "                       %s\n" "${PY_MODULES[@]}"
echo
echo -e "  Run from terminal  : ${BOLD}pachul${RESET}"
echo -e "  Or launch from     : ${BOLD}Applications → System → Pachul${RESET}"
echo
